name: smart_grid_view_nls
description: A responsive grid view that changes it's cross axis child count based on the available horizontal size.
version: 0.2.2
homepage: https://github.com/JoDeveloper/smart_grid_view_nls

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
